package:
  name: ros-noetic-mavlink
  version: 2022.8.8
source:
  git_url: https://github.com/mavlink/mavlink-gbp-release.git
  git_rev: release/noetic/mavlink/2022.8.8-1
  folder: ros-noetic-mavlink/src/work
  patches:
    - patch/ros-noetic-mavlink.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 14
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - future
    - lxml
    - python
    - ros-distro-mutex 0.3 noetic
  run:
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-catkin
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
